### ISSUE TITLE
留言板

### ISSUE THREAD

**Issue by LailuoA77** [LailuoA77/ly-auto-xuexiqiangguo#1]
大家有问题，有解决方法可以在这里留言，看见了就会回复

**Comment by 13753591385** [comment]
不错，不错！感觉题库是不是小，有4.7m的题库！也不知道对不对

**Comment by 13753591385** [comment]
华为p30学小视频只在页面不点进去每个小视频，其他都OK

**Comment by LailuoA77** [comment]
> 华为p30学习小视频，不点进去每个小视频，其他都OK

有报什么信息没有，或者底下的弹窗有消息没有，只是卡在那里吗？

**Comment by 13753591385** [comment]
> > 华为p30学习小视频，不点进去每个小视频，其他都OK
> 
> 有报什么信息没有，或者底下的弹窗有消息没有，只是卡在那里吗？

啥也不报，正常读剩余秒数。今早上又出现个专项答题进去不答题弹窗出现一堆红色英文！

**Comment by 13753591385** [comment]
你这边更新main. js我们下载的APP自动更新吗？还是要重新下载

**Comment by LailuoA77** [comment]
> 你这边更新main. js我们下载的APP自动更新吗？还是要重新下载

发布了修复版本，可以试一下

**Comment by 13753591385** [comment]
刚又试过了，还是小视频不点进去，只读秒数手动第一下帮点进去就好了。还有个不知道是不是读文章没有记忆，剩一分不够，然后反复读一篇文章。无限循环！几率性出现！四人赛第一次各种原因不得满分第二次就可以！要么愣住不答题，要的错误，提个建议可否设置答三次第一次不作答然后答第二三次！建议有点过分啊，可无视！😝😝总体挺不错💪👍👍👏👏

**Comment by LailuoA77** [comment]
答题是题库的问题，暂时无法解决。就算禁掉了某次，也会出现在其他题目上，有机会在解决。其他的我在看看，小视频的话，在虚拟机上，多亲ai2pro 上，华为畅玩10plus 测试过没有问题，其他手机（我也没有那么多手机，主要还是在虚拟机上测试）没有做测试，文章问题我也有正在想办法解决。多谢支持

**Comment by dagang69** [comment]
能请教一下代码编译的方法吗

**Comment by dagang69** [comment]
小米8按照app程序有闪退的情况，每次打开要点两次，第一次闪退，第二次才能成功进入app，不知怎么原因

**Comment by LailuoA77** [comment]
> 小米8按照app程序有闪退的情况，每次打开要点两次，第一次闪退，第二次才能成功进入app，不知怎么原因

是学习强国软件吗？软件等待延时有点短，建议先开强国软件，在开这个辅助程序，，
我用的autojs 7.0 直接就能生成

**Comment by dagang69** [comment]
> > 小米8按照app程序有闪退的情况，每次打开要点两次，第一次闪退，第二次才能成功进入app，不知怎么原因
> 
> 是学习强国软件吗？软件等待延时有点短，建议先开强国软件，在开这个辅助程序，，
> 我用的autojs 7.0 直接就能生成

是的，学习强国软件。按照你的方法，先开强国软件，再开辅助依然如此，重启手机以后情况没有改变，通常经过3次左右闪退，才能正常加载进入程序。

**Comment by dagang69** [comment]
请教一下，用auto.js pro 7连接vscode想编译main.js，提示pro 7版本太低，你们遇到过这种问题吗？还是说编译的环境不是用vscode

**Comment by LailuoA77** [comment]
> 请教一下，用auto.js pro 7连接vscode想编译main.js，提示pro 7版本太低，你们遇到过这种问题吗？还是说编译的环境不是用vscode

是在安卓手机里面的autojs 里面直接生成，想办法将源文件导入到手机中，auto.js pro 7以后的软件不支持学习强国了，无法控制了。

**Comment by 13753591385** [comment]
小视频不需要12个，之前6个就OK！视频时长会有广播补够！

**Comment by dagang69** [comment]
> > 请教一下，用auto.js pro 7连接vscode想编译main.js，提示pro 7版本太低，你们遇到过这种问题吗？还是说编译的环境不是用vscode
> 
> 是在安卓手机里面的autojs 里面直接生成，想办法将源文件导入到手机中，auto.js pro 7以后的软件不支持学习强国了


Error: Module "" not found. (file:///android_asset/modules/jvm-npm.js#96)
Error: Module "" not found.
    at Require (file:///android_asset/modules/jvm-npm.js:96:0)
    at /storage/emulated/0/脚本/ly-auto-xuexiqiangguo-main (6.19.1007)/ly-auto-xuexiqiangguo-main/main.js:6:0

已经导入auto.js7，执行main代码报错，能帮忙看看是啥问题么

**Comment by dagang69** [comment]
大佬发布提供一份上个版本打包的源码么，发现之前clone的main代码在更新，其他文件没跟上，是我这里执行报错的原因

**Comment by dagang69** [comment]
能发个auto.js的安装文件么？不知是不是用的版本没对，始终执行不了，好苦恼

**Comment by dagang69** [comment]
感谢大佬分享的代码，辛苦。
1.在模拟器上安装autojspro7成功运行最新的main.js，发现了一个问题，在mian代码行#714报错app闪退，但再次打开就可以使用。
2.百灵的短视频很多没有60秒，学习的计分逻辑可能存在问题，学完一个视频不足60秒，不能得分。

**Comment by LailuoA77** [comment]
由于autojspro7兼容较差，准备分支autojs 4 ，今天更新了主程序，修复了一些bug。目前还有有这样的问题，新的题目（极少数）选项会少几个，然而题库的答案仍然是ABCD选项模式，会出现卡死情况，暂时没有解决，请手动处理。如果遇到了可以在这里报告题目和答案，我这里更新。

**Comment by 13753591385** [comment]
发个最新的压缩包吧，大神！

**Comment by kugookill** [comment]
很好，但是专项答题很不准确。。。不会根据提示答题。

**Comment by 13753591385** [comment]
个人想把每周专项循环函数和无限下滑删除了，不知道怎么删，删哪一块？求大神们指点！要不每天下滑太费时间，还是无限循环

**Comment by Gamesrevo** [comment]
默认运行建议取消每周和专项答题，视频浏览可以选择百灵“dang史”

**Comment by shuaiqingm** [comment]
使用autojs pro运行脚本出错

23:07:06.771/E: Error: Module "" not found. (file:///android_asset/modules/jvm-npm.js#96)
Error: Module "" not found.
    at Require (file:///android_asset/modules/jvm-npm.js:96:0)
    at /storage/emulated/0/脚本/ly-auto-xuexiqiangguo-main/main.js:6:0

**Comment by huangdiv** [comment]
使用autojs 4.1.1 Alpha2版本，启动源代码，main.js 第18行报错，注释掉自动检测更新就正常了
```
07:58:44.712/E: Wrapped android.os.NetworkOnMainThreadException (file:///android_asset/modules/__http__.js#49) 
Wrapped android.os.NetworkOnMainThreadException
at file:///android_asset/modules/__http__.js:49:0
at /storage/emulated/0/脚本/ly-auto-xuexiqiangguo-ds01.01/main.js:18:0
```

**Comment by huangdiv** [comment]
使用autojs 4.1.1 Alpha2版本，启动源代码，main.js 第18行报错，注释掉自动检测更新就正常了
```
07:58:44.712/E: Wrapped android.os.NetworkOnMainThreadException (file:///android_asset/modules/__http__.js#49) 
Wrapped android.os.NetworkOnMainThreadException
at file:///android_asset/modules/__http__.js:49:0
at /storage/emulated/0/脚本/ly-auto-xuexiqiangguo-ds01.01/main.js:18:0
```

**Comment by v09v** [comment]
> 默认运行建议取消每周和专项答题，视频浏览可以选择百灵“dang史”

同感

**Comment by kugookill** [comment]
可参照代码加入分享、收藏及评论功能

**Comment by LailuoA77** [comment]
最近比较忙，兄弟们可以自行下载更改

**Comment by LailuoA77** [comment]
仅限于安卓7.0以上，联想模拟器上应用最优

**Comment by LiuNet2** [comment]
这是用哪个IDE开发的啊？Hbuilder吗？

**Comment by taslord** [comment]
兄弟，还更新吗？没有软件用了。

**Comment by LailuoA77** [comment]
最近正在忙工作上的事情，没有更新了，但是软件应该是可以运行的

**Comment by Wang-zhechao** [comment]
Have an error about  ---  java.net.SocketException: Connection reset(file://android_asset/modules/__http__.js#88)

**Comment by lukemin** [comment]
update.js 能否更新一下？ 能否使用https://github.com/Mondayfirst/XXQG_TiKu 题库文件？

**Comment by mingleichen** [comment]
这几天对战答题不会自动答题，能否修复一下，谢谢

**Comment by LailuoA77** [comment]
对战答题更新了，无法获取道题目和选项，目前是不可用状态了

**Comment by mastersir-lab** [comment]
大佬，我感觉可能不答题是因为本身手机配置的原因，进入答题的时间比较慢。希望配置里面添加一个可控参数，用来调整等待加载进入答题页面的时间，如果是其他原因希望大佬解决一下，支持！还有题库更新不可用了

**Comment by 173539949840** [comment]
> 大家有问题，有解决方法可以在这里留言，看见了就会回复
四人赛和双人对战 修复一下吧

**Comment by 173539949840** [comment]
> 对战答题更新了，无法获取道题目和选项，目前是不可用状态了

是什么原因呢？ 题库还是？

**Comment by hongyits** [comment]
> 使用autojs pro运行脚本出错
> 
> 23:07:06.771/E: Error: Module "" not found. (file:///android_asset/modules/jvm-npm.js#96) Error: Module "" not found. at Require (file:///android_asset/modules/jvm-npm.js:96:0) at /storage/emulated/0/脚本/ly-auto-xuexiqiangguo-main/main.js:6:0

同求。。。

**Comment by Gamesrevo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
